classes: 'class.txt'                              # write here
network: 'vgg16'                                  # write here, (default:'vgg16' or 'vgg19')

nc: 1
img_size: [224, 224, 3]
workers: 4

vgg16:
  [[64, 64],
   [128, 128], 
   [256, 256, 256], 
   [512, 512, 512],
   [512, 512, 512]]

vgg19:
  [[64, 64],
   [128, 128], 
   [256, 256, 256, 256], 
   [512, 512, 512, 512],
   [512, 512, 512, 512]]

fc_layer:
  [4096, 4096]

DATASET:
  root_path: '/Users/bolero/dc/dataset/cifar10'   # write here
  ext: 'png'                                      # write here

TRAIN:
  exp: 'run'                                      # write here
  factor: 0.1
  patience: 5
  epoch: 30
  batch_size: 16
